[package]

name = "gitostat"
version = "0.2.0"
authors = ["Arthur Skobara <skobara.arthur@gmail.com>"]

[dependencies]
git2 = "*"
chrono = "*"
docopt = "*"
rustc-serialize = "*"
regex = "*"
regex_macros = "*"
